# CMPE 140 - Workshop 5 (Fall 23-24)

# Afternoon Session

## Question 1

Below are two data frames, containing information about students. 


| Name    | Major | Math | Science |
| -----   | ---   | ---- | ------- |
| Alice   |  EC   |  80  | 90 |
| Bob     |  MGMT |  90  | 80 |
| Charlie |  POLS |  70  | 75 |


| Name    | Major | English | History |
| -----   | ---   | ----    | ------- |
| Alice   |  EC   |    85   |    90   |
| Charlie |  POLS |    75   |    80   |
| Dave    |  EC   |    80   |    85   |

First data frame contains information about the students' names, majors, and grades in Math and Science, while second data frame contains information about the students' names, majors, and grades in English and History. 

Write a function called ``merge_df`` which takes two data frames as input, merges them into a single data frame and returns the resulting data frame which also includes the average grade for each student in the right-most column as such:


```r
merge_df(df1,df2)

     Name Major Math Science English History AvgGrade
1   Alice    EC   80      90      85      90    86.25
2     Bob  MGMT   90      80      NA      NA    85.00
3 Charlie  POLS   70      75      75      80    75.00
4    Dave    EC   NA      NA      80      85    82.50
```

## Question 2

Write a function called ``count_high_values`` which accepts a data frame and a column name as inputs. The function should categorize the values in the specified column into two categories: low and high.

- Values which are less than or equal to the mean of all values in that column are classed as low.
- Values greater than the mean are classed as high.


The function should return a single number representing the count of high values in the specified column.
Example outputs :

```r
count_high_values(mtcars,"hp")
[1] 15
count_high_values(mtcars,"mpg")
[1] 14
count_high_values(iris,"Sepal.Length")
[1] 70
```

## Question 3

Convert the following information about the intensities of the daily exercises done by an individual in a week to a factor. 

| days      | intensity |
|-----------|-----------|
| monday    | intense   |
| tuesday   | light     |
| wednesday | none      |
| thursday  | intense   |
| friday    | light     |
| saturday  | none      |
| sunday    | none      |

Write a function ``weekly_ex`` which takes a factor argument **f** that contains the intensity of the daily exercises that a person does in a week. Your function should find the days of the week that the individual works out (so the intensity must be "intense" or "light") and submit those days in a list's first element which has **"well_done"** as a name. Then it should find the days that the individual does not work out (so the intensity must be "none") and submit those in the list's second element that has **"shame"** as a name. Lastly, your function should replace the "none"s in the factor **f** with "light"s and submit the new factor in the last element of the list which has a name of **"next_week"** (remember doing the necessary arrangement in the levels of the factor). 

Your output should be:

```r
weekly_ex(ex_fac)

$well_done
[1] "monday"   "tuesday"  "thursday" "friday"  

$shame
[1] "wednesday" "saturday"  "sunday"   

$next_week
[1] intense light   light   intense light   light   light  
Levels: intense light
```